# ============================================================
# DIGITRANS-CM — CRM Frontend
# Dockerfile Angular (Multi-stage build + Nginx)
# Auteur : Équipe CRM — Gaouaffo Nanfah
# ============================================================

# ---- STAGE 1 : Build Angular ----
FROM node:20-alpine AS builder

WORKDIR /app

# Copier package.json d'abord (cache Docker)
COPY package*.json ./
RUN npm ci --silent

# Copier le code source Angular et builder
COPY . .
RUN npm run build -- --configuration=production

# ---- STAGE 2 : Runtime Nginx ----
FROM nginx:1.25-alpine

# Supprimer la config Nginx par défaut
RUN rm /etc/nginx/conf.d/default.conf

# Copier notre configuration Nginx personnalisée
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copier le build Angular
COPY --from=builder /app/dist/crm-frontend/browser /usr/share/nginx/html

# Créer utilisateur non-root
RUN adduser -D -u 1001 nginxuser && \
    chown -R nginxuser:nginxuser /usr/share/nginx/html && \
    chown -R nginxuser:nginxuser /var/cache/nginx && \
    touch /var/run/nginx.pid && \
    chown -R nginxuser:nginxuser /var/run/nginx.pid

USER nginxuser

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=5s \
  CMD wget -qO- http://localhost:80 || exit 1

CMD ["nginx", "-g", "daemon off;"]
